[package]
name = "aqf"
version = "0.1.0"
authors = ["David J. Lee <djl5@williams.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
murmur3 = "0.5.1"
rand = { version = "0.8.2", features = ["small_rng"]}